### PR TITLE
fix: avoid GCS caching the index file

### PR DESCRIPTION
**Pull request by rawlingsj**
more details on Caching can be found here https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#cache-control_1

Added this PR as Work In Progress while we validate using our pipelines

### CODE REVIEW

**Comment by rawlingsj** [comment]
We've been running with this for a few days now and it's working great!

**Comment by rawlingsj** [comment]
Is there any feedback on this PR?  Would love to see it get merged as we are reliant on it now and it's been working great.  In fact without this change I think users will run into issues if a helm release of a chart follows another in quick succession before the bucket cache has been updated.

**Comment by benjlevesque** [comment]
Looking forward for this 👍

**Comment by benjlevesque** [comment]
@hayorov does it look good to you?

**Comment by rawlingsj** [comment]
@hayorov is it possible to merge this PR please?  Without it users run into caching issues of the index.yaml.  We have been using it for over a month to release well over a hundred charts and it is working great.

**Comment by rawlingsj** [comment]
Yay - thanks @hayorov

**Pull request merged**
